### ISSUE TITLE
你好，vlc读流提示错误

### ISSUE THREAD

**Issue by SoulProficiency** [1514LT/FFmpegAndOpenCVPushRTSP#2]
1.我按照要求运行程序，将输入的url改为本地的视频glmark2.mp4
2.运行适合自己版本的mediamtx，端口正常
3.运行主程序，端口提示正常，推流成功
4.使用vlc读流提示错误。
path of a SETUP request must end with a slash. this typically happens when vlc fails a request and then switches to an unsupport RTSP dialect

**Comment by 1514LT** [comment]
RTPS和MP4的格式不同，得先把glmark2.mp4推为RTPS视频流，让在去掉程序（glmark2——&gt;RTPS&nbsp; &amp;&amp; url：RTPS ——&gt; newurl:RTPS）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1514LT/FFmpegAndOpenCVPushRTSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月5日(星期五) 晚上6:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1514LT/FFmpegAndOpenCVPushRTSP] 你好，vlc读流提示错误 (Issue #2)





 
1.我按照要求运行程序，将输入的url改为本地的视频glmark2.mp4
 2.运行适合自己版本的mediamtx，端口正常
 3.运行主程序，端口提示正常，推流成功
 4.使用vlc读流提示错误。
 path of a SETUP request must end with a slash. this typically happens when vlc fails a request and then switches to an unsupport RTSP dialect

**Comment by SoulProficiency** [comment]
目前未去修正，cv读流正常
